name: "Create Tags"
on:
  pull_request:
    types: [closed]

jobs:
  preflight_check:
    name: 'Pre release checks'
    runs-on: ubuntu-latest
    steps:
      - uses: q4chrisj/preflight-check@main
  create_tags:
    name: 'Create release tags'
    runs-on: ubuntu-latest
    steps:
      - uses: q4chrisj/tag-bot@develop
        with: 
          token: ${{ github.token }}
