
name: "Preflight Checks"
on:
  push

jobs:
  preflight_check:
    name: 'Pre release checks'
    runs-on: ubuntu-latest
    steps:
      - uses: q4chrisj/preflight-checklist@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
