
name: "Preflight Checks"
on:
  workflow_dispatch:

jobs:
  preflight_check:
    name: 'Pre release checks'
    runs-on: ubuntu-latest
    steps:
      - uses: q4chrisj/preflight-checklist@main
        with: 
          token: ${{ github.token }}
