
name: "Preflight Checks"
on:
  workflow_dispatch:

jobs:
  preflight_check:
    name: 'Pre release checks'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: q4chrisj/preflight-checklist@main
        with: 
          token: ${{ github.token }}
          target_aws_key_id: 'secret_key_test'
          target_aws_secret_access_key: 'secret_access_test'
